# Application Configurations
application: smiling-cistern-120719
version: 1
runtime: python27
threadsafe: true
api_version: 1

# Handlers tell App Engine how to route incoming requests
handlers:

# Routing to static resources
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index\.html
  secure: always

# Handler for endpoints
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION
  secure: always

# Including third-party libraries
libraries:

-name: endpoints
  version: 1.0
